### ISSUE TITLE
[Linter] Error running ESLint Error: require(...).getLocationFromRangeIndex is not a function(…)

### ISSUE THREAD

**Issue by nwaywood** [not-an-aardvark/eslint-plugin-prettier#11]
ESLint is failing to run for me with `eslint-plugin-prettier` rules activated (i.e. with `"rules": { "prettier/prettier": "error" }` set). 

This is the stacktrace from atom:

![image](https://cloud.githubusercontent.com/assets/3773641/24233265/3a20a572-0fe5-11e7-8c9b-321fe075744e.png)

As it says in the stacktrace, the error comes from [this](https://github.com/not-an-aardvark/eslint-plugin-prettier/blob/master/lib/rules/prettier.js) file on line 30 where it calls `require('eslint/lib/ast-utils').getLocationFromRangeIndex(...)`.

Upon inspection of [eslint/lib/ast-utils](https://github.com/eslint/eslint/blob/master/lib/ast-utils.js) I see that the function no longer exists. The function was removed in [this](https://github.com/eslint/eslint/commit/dad20ad940eedcc3f2e3f72b3f182dda5a8e700c#diff-6198b73cda8ab9ac49ed872ead7fb268) commit.

**Comment by not-an-aardvark** [comment]
Does this still occur with `eslint-plugin-prettier@2.0.1`?

**Comment by nwaywood** [comment]
Yes. Here are the devDeps from my `package.json`

![image](https://cloud.githubusercontent.com/assets/3773641/24233444/5e547cce-0fe6-11e7-91dd-92042d9a5884.png)

**Comment by nwaywood** [comment]
Not sure if this is important/relevant but this error only happens when the file does not confirm to the prettier format. If a file is already formatted by prettier than the linter doesn't log this error

**Comment by not-an-aardvark** [comment]
Hmm, that's odd. You're right that the function from `eslint/lib/ast-utils` no longer exists, but the ternary expression [here](https://github.com/not-an-aardvark/eslint-plugin-prettier/blob/master/lib/rules/prettier.js#L28-L33) is intended to check for the existence of `sourceCode.getLocFromIndex`, which was added in the same commit that the other function was removed.

What version of eslint do you currently have installed? (Your package.json just shows `^3.14.1`, but I'm wondering if there's a particular eslint version where this breaks. It seems to work fine for me with the latest version of eslint.)

**Comment by nwaywood** [comment]
Yes the version of eslint I am using is `^3.14.1`, I just updated eslint to the latest (`^3.18.0`) and I get the same error. Would you like me to test a different version?

**Comment by not-an-aardvark** [comment]
From your stack trace screenshot, I see that you're using eslint from atom. Have you tried restarting atom? I wonder if it's caching the version of eslint somehow.

(Apart from that, I'm not sure what the problem would be given that it seems to be working on master and for other people.)

**Comment by nwaywood** [comment]
Sorry I made an edit to my previous comment, you most not have noticed it. After a restart of atom it is working now with version `^3.18.0` of eslint. I'll close this since its only an issue with an old version of eslint

**Comment by not-an-aardvark** [comment]
Great, glad to hear it's working now.
