### ISSUE TITLE
Make extendable preset

### ISSUE THREAD

**Issue by MoeSattler** [not-an-aardvark/eslint-plugin-prettier#12]
Wouldn't it make sense to have this as a preset instead of a plugin? This way you would make rules overwritable and hence have it compatible with `prettier-eslint`.

E.g. 
```
{
  "extends": "prettier",
  "rules": {
    "quotes": ["error", "single"],
   }
}
```

instead of 
```
{
    "plugins": [
        "prettier"
    ],
    "rules": {
        "prettier/prettier": ["error", {"singleQuote": true}]
    }
}
```

**Comment by not-an-aardvark** [comment]
I don't see how this would work -- if this was a preset, it doesn't seem like it would be possible to pass config options to prettier. Could you clarify?

**Comment by MoeSattler** [comment]
@not-an-aardvark 
Forgive if I am wrong, and this might be a bit of a naive question, I am still very new to prettier. 
But my impression was, that all prettier rules do already exist in one way or another in eslint. So do we really need the option of passing a config to prettier? 
E.g. why use `config.singleQuote` when you could just read out `rules.quotes`. (see the example above).

**Comment by MoeSattler** [comment]
@not-an-aardvark 
I think I was misunderstanding what this project wants to achieve. 
It seems like the main goal is to format code according to prettier with the `--fix` command. 
I was looking for something that would just indicate where code is not formatted according to prettier rules.
