### ISSUE TITLE
Use `formatAST`.

### ISSUE THREAD

**Issue by jlongster** [not-an-aardvark/eslint-plugin-prettier#2]
In the code there is this comment:

```
// This isn't really very performant (prettier needs to reparse the text).
// However, I don't think it's possible to run `prettier` on an ESTree AST.
```

We do provide a `formatAST` function for passing in an AST. What you can't do is run both `eslint --fix` and `prettier.format` in the same pass because they both make modifications to text, not AST, so they both output text (I think eslint might be able to output some generic structure, but we'd have to re-parse it anyway).

I'm not too familiar with eslint plugins, but if you're just running `eslint` and you get an AST you should be able to use it.

**Comment by not-an-aardvark** [comment]
Does `formatAST` provide a way to include comments? Thinking about this again, if I just passed the AST to prettier, then all the comments would be get removed, which is undesirable.

Also, does `formatAST` accept ESTree ASTs? I know prettier uses babylon for parsing, which has some nodes that are different from ESTree (which is what ESLint uses).

**Comment by not-an-aardvark** [comment]
Closing this since passing an AST to prettier isn't feasible as far as I can tell. (If it is possible to do this while retaining comments, a PR for it would be appreciated.)
