### ISSUE TITLE
Prettier trailingComma setting is now a string

### ISSUE THREAD

**Issue by ndelangen** [not-an-aardvark/eslint-plugin-prettier#3]
The trailingComma option has been changed to the following possible values:
```
  // Controls the printing of trailing commas wherever possible. Valid options:
  // "none" - No trailing commas
  // "es5"  - Trailing commas where valid in ES5 (objects, arrays, etc)
  // "all"  - Trailing commas wherever possible (function arguments)
  //
  // NOTE: Above is only available in 0.19.0 and above. Previously this was
  // a boolean argument.
  trailingComma: "none",
```
https://github.com/prettier/prettier#api

But this plugin still enforces it to be a boolean.
<img width="513" alt="screen shot 2017-02-22 at 16 50 38" src="https://cloud.githubusercontent.com/assets/3070389/23219340/1616460a-f91f-11e6-8957-583b544493de.png">

**Comment by not-an-aardvark** [comment]
This plugin doesn't do any validation of prettier arguments, so I think that error is coming from prettier itself. Is it possible that you have an old version of prettier installed?

**Comment by benmccormick** [comment]
I also hit this problem.  Note that the comment in the screenshot says that this is `0.19.0+`, but the latest version released is `0.18.0`.  Perils of reading from master on a github repo

**Comment by not-an-aardvark** [comment]
If I'm understanding correctly, this is an issue with `prettier` releases and not `eslint-plugin-prettier`, right?

**Comment by benmccormick** [comment]
@not-an-aardvark yep, I don't think there's any problem with this repo

**Comment by not-an-aardvark** [comment]
Ok, thanks. Closing this issue.
