### ISSUE TITLE
linter semicolon errors

### ISSUE THREAD

**Issue by MayasHaddad** [not-an-aardvark/eslint-plugin-prettier#5]
I added the plugin to my .eslintrc 
![screen shot 2017-03-10 at 16 28 53 2](https://cloud.githubusercontent.com/assets/1893921/23801092/2141a398-05af-11e7-9026-95ac12f2f785.png)

But I still get:
![screen shot 2017-03-10 at 16 29 22 2](https://cloud.githubusercontent.com/assets/1893921/23801163/6dd3f544-05af-11e7-87a2-14a4c2bab6a9.png)

Note that I get the error when I run `eslint .` as well.

Am I missing something? 🤔

**Comment by not-an-aardvark** [comment]
This plugin works best if you disable all other ESLint rules relating to code formatting, and only enable rules that detect patterns in the AST. (If another active ESLint rule disagrees with `prettier` about how code should be formatted, it will be impossible to avoid lint errors.) You can use [eslint-config-prettier](https://github.com/lydell/eslint-config-prettier) to disable all formatting-related ESLint rules. If your desired formatting does not match the `prettier` output (e.g. if you don't want semicolons), you should use a different tool such as [prettier-eslint](https://github.com/kentcdodds/prettier-eslint) instead.
