### ISSUE TITLE
Clearer documentation about setting node environment for sublime to what prettier was installed with

### ISSUE THREAD

**Issue by mlunoe** [not-an-aardvark/eslint-plugin-prettier#6]
After installing prettier and following the instructions I was hitting this issue:
```
/Users/ml/.nvm/versions/node/v4.4.4/lib/node_modules/prettier/bin/prettier.js:5
const fs = require("fs");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

I wasn't sure what the problem was. After some digging, I found that I needed to have my node environment for sublime (for me project specific) as `prettier` was installed with. Setting this in my .sublime-project file solved it for me:
```js
  "settings": {
    "js_prettier": {
      "prettier_cli_path": "/Users/ml/.nvm/versions/node/v4.4.4/bin/prettier",
      "node_path": "/Users/ml/.nvm/versions/node/v4.4.4/bin/node"
    }
  }
```

This was not super obvious to me. Could this be documented clearer somewhere?

Related issue: https://github.com/prettier/prettier/issues/99#issuecomment-286508507

**Comment by not-an-aardvark** [comment]
I'm not sure I understand the issue. Is the problem that you were running an old version of Node?

**Comment by mlunoe** [comment]
Nope, the problem was that my environment (Sublime) was running a different version of node than what I used to install prettier with (and use in my project). So I had to point to sublime to use the same version of Node for its environment as I am using for prettier for it to work.

**Comment by not-an-aardvark** [comment]
Thanks for clarifying. That seems like an editor-specific issue, so I don't think this is the right place to document it. (This repo is just a plugin for a command-line tool -- it's not tied to any editor.) It might be better to clarify this in your editor integration's docs instead.

**Comment by mlunoe** [comment]
You are right! Not the right repo. Sorry for the inconvenience!
