### ISSUE TITLE
Fails with eslint v3.12.0

### ISSUE THREAD

**Issue by jasonLaster** [not-an-aardvark/eslint-plugin-prettier#8]
Neither `getLocationFromRangeIndex` or `getLocFromIndex`. There should probably be a better warning message like this library requires a dep greater than  `3.12.0`.

**Comment by not-an-aardvark** [comment]
The package has a `peerDependency` of `eslint: ^3.14.1` [here](https://github.com/not-an-aardvark/eslint-plugin-prettier/blob/3fefbf3fc1f7b4507c3bb050a24eeda9c6231c4b/package.json#L28), so I would have expected npm to raise a warning for this. Is it not doing that for some reason?

**Comment by jasonLaster** [comment]
Could it be that I'm using a global eslint and local prettier and atom
plugin?

**Comment by not-an-aardvark** [comment]
Yes, if you run eslint globally it will only be able to find globally-installed plugins. For more information see the [eslint docs](https://github.com/eslint/eslint/blob/04915720e1704831cd8f56a638ce7a35dd809ab7/README.md#installation-and-usage).

Personally, I would recommend always installing everything locally.

**Comment by jasonLaster** [comment]
That's good to know. The local option works in all but one case for me ;)

Firefox's setup is weird!
